// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJs-j4E-AA-pik0k0qLZvmpVcrvpkDyRU',
    appId: '1:526893383781:web:2827212ad27aa9271a468c',
    messagingSenderId: '526893383781',
    projectId: 'project-65f35',
    authDomain: 'project-65f35.firebaseapp.com',
    storageBucket: 'project-65f35.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF5P7dmpSPutKfgeNiRyOMAZGgrVwTCNo',
    appId: '1:526893383781:android:804fc4e1cc153c0e1a468c',
    messagingSenderId: '526893383781',
    projectId: 'project-65f35',
    storageBucket: 'project-65f35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3cvTpqQbRLViqCgon2QgWRksaS19AEO4',
    appId: '1:526893383781:ios:93615aa8fc9bd0f41a468c',
    messagingSenderId: '526893383781',
    projectId: 'project-65f35',
    storageBucket: 'project-65f35.appspot.com',
    iosClientId: '526893383781-o2d94i8jftbvaf3b3dou22sdtj9n1lgl.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3cvTpqQbRLViqCgon2QgWRksaS19AEO4',
    appId: '1:526893383781:ios:93615aa8fc9bd0f41a468c',
    messagingSenderId: '526893383781',
    projectId: 'project-65f35',
    storageBucket: 'project-65f35.appspot.com',
    iosClientId: '526893383781-o2d94i8jftbvaf3b3dou22sdtj9n1lgl.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
